---
enablePrometheus: true
enableCertManager: true
enableVisibilityAPF: false
enableKueueViz: true
controllerManager:
  featureGates: []
  manager:
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
  replicas: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
managerConfig:
  controllerManagerConfigYaml: |-
    apiVersion: config.kueue.x-k8s.io/v1beta1
    kind: Configuration
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: :8443
      enableClusterQueueResources: true
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: c1f6bfd2.kueue.x-k8s.io
    controller:
      groupKindConcurrency:
        Job.batch: 5
        Pod: 5
        Workload.kueue.x-k8s.io: 5
        LocalQueue.kueue.x-k8s.io: 1
        ClusterQueue.kueue.x-k8s.io: 1
        ResourceFlavor.kueue.x-k8s.io: 1
    clientConnection:
      qps: 50
      burst: 100
    manageJobsWithoutQueueName: false
    managedJobsNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: [ kube-system, kueue-system, monitoring ]
    internalCertManagement:
      enable: false
    integrations:
      frameworks:
      - "batch/job"
metricsService:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
# overbodig icm met alloy, toch gezet op een value, omdat de default de monitoring namespaces is (en dat verwarrend is)
metrics:
  prometheusNamespace: alloy
